// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql"
)

type User struct {
	ID    int64          `json:"id"`
	Name  string         `json:"name"`
	Phone sql.NullString `json:"phone"`
}
